name: Trigger auto deployment for mayank-tech

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/mayank-tech-AutoDeployTrigger-a96adc99-20e2-4453-8948-71c6909b9c8b.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MAYANKTECH_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: mayanktechregistry.azurecr.io
          registryUsername: ${{ secrets.MAYANKTECH_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MAYANKTECH_REGISTRY_PASSWORD }}
          containerAppName: mayank-tech
          resourceGroup: DefaultResourceGroup-CCAN
          imageToBuild: mayanktechregistry.azurecr.io/mayank-tech:${{ github.sha }}
          dockerfilePath: Dockerfile

     

